# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-20 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language_Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '语言构成',
                'verbose_name_plural': '语言构成',
                'permissions': (('can_read_language_form_record', '读取语言构成权限'),),
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Language_Version_Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default=None, max_length=10, null=True, verbose_name='语言')),
                ('name', models.CharField(default=None, max_length=50, null=True, verbose_name='名称')),
            ],
            options={
                'verbose_name': '语言版本配置',
                'verbose_name_plural': '语言版本配置',
                'db_table': 'opsmanage_language_version_config',
                'permissions': (('can_read_language_version_config_record', '读取语言版本配置权限'), ('can_change_language_version_config_record', '更改语言版本配置权限')),
            },
        ),
        migrations.CreateModel(
            name='Operation_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oper_user', models.CharField(default=None, max_length=50, verbose_name='操作用户')),
                ('oper_name', models.CharField(default=None, max_length=100, verbose_name='名称')),
                ('oper_content', models.CharField(default=None, max_length=100, verbose_name='操作内容')),
                ('oper_type', models.CharField(default=None, max_length=100, verbose_name='操作类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '操作日志记录表',
                'verbose_name_plural': '操作日志记录表',
                'db_table': 'opsmanage_operation_log',
                'permissions': (('can_read_operation_log_record', '读取操作日志权限'), ('can_change_operation_log_record', '更改操作日志权限'), ('can_add_operation_log_record', '添加操作日志权限'), ('can_delete_operation_log_record', '删除操作日志权限')),
            },
        ),
    ]
