# -*- coding: utf-8 -*-
"""
Django settings for OpsManage project.

Generated by 'django-admin startproject' using Django 1.9.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
import djcelery
from celery import  platforms
from django.utils.translation import ugettext as _

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
''' celery config '''
djcelery.setup_loader()
BROKER_URL = 'redis://127.0.0.1:6379/3'
CELERY_RESULT_BACKEND = 'djcelery.backends.database.DatabaseBackend'
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'pickle'
CELERY_ACCEPT_CONTENT = ['json', 'pickle']
CELERYBEAT_SCHEDULER = 'djcelery.schedulers.DatabaseScheduler'
CELERY_TASK_RESULT_EXPIRES = 60 * 60 * 24
CELERYD_MAX_TASKS_PER_CHILD = 40
CELERY_TRACK_STARTED = True
CELERY_TIMEZONE='Asia/Riyadh'
platforms.C_FORCE_ROOT = True

REDSI_KWARGS_LPUSH = {"host":'127.0.0.1','port':6379,'db':3}
REDSI_LPUSH_POOL = None
SECRET_KEY = 'kd8f&jx1h^1m-uldfdo3d#10d9mbc-ijjz!tozusy@aw#h+875'

DEBUG = True

ALLOWED_HOSTS = ['*']

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'OpsManage',
    'rest_framework',
    'djcelery',
    'django_crontab',
    'django_extensions',
)

# CRONJOBS = (
#     ('2 0-23/1 * * *', 'OpsManage.cron.data_info_up', '>>/var/log/cron_job2.log'),
#     ('5 * * * 5', 'OpsManage.cron.data_week_info_up', '>>/var/log/cron_job5.log'),
#     ('6 * 2 * *', 'OpsManage.cron.data_month_info_up', '>>/var/log/cron_job6.log'),
#     ('3 5 */1 * *', 'OpsManage.cron.remain_day_up', '>>/var/log/cron_job3.log'),
#     ('1 0-23/1 * * *', 'OpsManage.cron.data_real_up', '>>/var/log/cron_job1.log'),
# 	('1 */1 * * *', 'OpsManage.cron.charge_from_game', '>>/var/log/cron_job1.log'),
#     # ('1 0 */1 * *', 'OpsManage.cron.report_day_quantity', '>>/var/log/cron_job_quantity.log'),
# )

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
)

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

ROOT_URLCONF = 'OpsManage.urls'

WSGI_APPLICATION = 'OpsManage.wsgi.application'



DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '127.0.0.1',  # 数据库主机
        'PORT': 3306,  # 数据库端口
        'USER': 'root',  # 数据库用户名
        'PASSWORD': 'a995405033',  # 数据库用户密码
        'NAME': 'abmanage'  # 数据库名字
    }
}

LANGUAGE_CODE = 'zh-hans'

LANGUAGES = (
    ('zh-hans', '中文'),
    ('en', '英文'),
)

LANGUAGES_SUPPORTED = ('en', 'zh-cn',)

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DEFAULT_CHARSET = 'utf-8'

FILE_CHARSET = 'utf-8'

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale'),
)

STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATIC_URL = '/static/'

TEMPLATE_CONTEXT_PROCESSORS = (
    'django.template.context_processors.i18n',
    'django.contrib.auth.context_processors.auth',
)

LOGIN_URL = '/login?next=/'

LOGIN_REDIRECT_URL = '/'
